# Generated by Django 5.1.2 on 2024-10-30 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('accidental_background', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('leftside_img', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('rightside_img', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('insurance_end_date', models.DateField()),
                ('ownership_type', models.CharField(choices=[('1st', '1st Owner'), ('2nd', '2nd Owner'), ('3rd', '3rd Owner')], max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.brand')),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.oiltype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
