# Generated by Django 5.1.2 on 2024-11-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_carforrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carforrent',
            name='rent_car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/rent_car_images'),
        ),
    ]
