# Generated by Django 5.1.2 on 2024-11-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_carforrent_rent_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carforrent',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carforrent',
            name='registration_number',
            field=models.CharField(default='Unknown Location', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carforrent',
            name='whatsapp_number',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
