# Generated by Django 5.1.2 on 2024-11-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_carforrent_location_carforrent_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carforrent',
            name='rent_car_image',
        ),
        migrations.AddField(
            model_name='carforrent',
            name='car_image',
            field=models.ImageField(default='', upload_to='car_images/rent_car_images/'),
            preserve_default=False,
        ),
    ]
