# Generated by Django 5.1.2 on 2024-11-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_carforrent_rent_car_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carforrent',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='carforrent',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='carforrent',
            name='user',
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='mileage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='registration_number',
            field=models.CharField(max_length=15),
        ),
    ]
