# Generated by Django 5.1.2 on 2024-11-04 05:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_carforrent_car_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carforrent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='carforrent',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='carforrent',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='carforrent',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carforrent',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.brand'),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='oil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.oiltype'),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='rent_car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/rent_car_images'),
        ),
    ]
