# Generated by Django 5.1.2 on 2024-11-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_carforrent_location_and_more'),  # Ensure this points to a stable migration
    ]

    operations = [
        # Remove unnecessary fields
        migrations.RemoveField(
            model_name='carforrent',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='carforrent',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='carforrent',
            name='rent_car_image',
        ),

        # Add new fields with appropriate defaults
        migrations.AddField(
            model_name='carforrent',
            name='car_image',
            field=models.ImageField(default='No Image', upload_to='cars/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carforrent',
            name='location',
            field=models.CharField(default='No location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carforrent',
            name='registration_number',
            field=models.CharField(max_length=50),  # Adjusted max_length
        ),
        migrations.AddField(
            model_name='carforrent',
            name='whatsapp_number',
            field=models.CharField(max_length=50),  # Adjusted max_length
        ),

        # Alter existing fields
        migrations.AlterField(
            model_name='carforrent',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='mileage',
            field=models.FloatField(),
        ),
    ]
