# Generated by Django 5.1.2 on 2024-11-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_carforrent_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carforrent',
            name='registration_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carforrent',
            name='whatsapp_number',
            field=models.CharField(max_length=15),
        ),
    ]
